from flask import Flask, render_template

def create_app():
  app = Flask(__name__)# pass the name of the current file

  @app.route('/') # decorator
  def index():#function name is view
      title = "Map"
      discricts =  {"cfo": '#000000',
        "szfo": '#54cbba',
        "yfo": '#f9768e',
        "skfo": '#9a5597',
        "pfo": '#30cb05',
        "urfo": '#682a43',
        "sfo": '#16acdb',
        "dfo": '#fbc520',
        'bel': '#54cbba',
        'bry': '#54cbba',
        'vla': '#54cbba',
        'vor': '#54cbba',
        'iva': '#54cbba',
        'klu': '#54cbba',
        'kos': '#54cbba',
        'krs': '#54cbba',
        'lip': '#54cbba',
        'mos': '#54cbba',
        'mow': '#54cbba',
        'orl': '#54cbba',
        'rya': '#54cbba',
        'smo': '#54cbba',
        'tam': '#54cbba',
        'tve': '#54cbba',
        'tul': '#54cbba',
        'yar': '#54cbba',
        'ark': '#54cbba',
        'vlg': '#54cbba',
        'kgd': '#54cbba',
        'kr': '#54cbba',
        'ko': '#54cbba',
        'len': '#54cbba',
        'mur': '#54cbba',
        'nen': '#54cbba',
        'ngr': '#54cbba',
        'psk': '#54cbba',
        'spe': '#54cbba',
        'ad': '#54cbba',
        'ast': '#54cbba',
        'vgg': '#54cbba',
        'kl': '#54cbba',
        'kda': '#54cbba',
        'sev': '#54cbba',
        'kry': '#54cbba',
        'ros': '#54cbba',
        'da': '#54cbba',
        'in': '#54cbba',
        'kb': '#54cbba',
        'kc': '#54cbba',
        'se': '#54cbba',
        'sta': '#54cbba',
        'ce': '#54cbba',
        'ba': '#54cbba',
        'kir': '#54cbba',
        'me': '#54cbba',
        'mo': '#54cbba',
        'niz': '#54cbba',
        'ore': '#54cbba',
        'pnz': '#54cbba',
        'per': '#54cbba',
        'sam': '#54cbba',
        'sar': '#54cbba',
        'ta': '#54cbba',
        'ud': '#54cbba',
        'uly': '#54cbba',
        'cu': '#54cbba',
        'kgn': '#54cbba',
        'sve': '#54cbba',
        'tyu': '#54cbba',
        'khm': '#54cbba',
        'che': '#54cbba',
        'yan': '#54cbba',
        'alt': '#54cbba',
        'al': '#54cbba',
        'bu': '#54cbba',
        'zab': '#54cbba',
        'irk': '#54cbba',
        'kem': '#54cbba',
        'kya': '#54cbba',
        'nvs': '#54cbba',
        'oms': '#54cbba',
        'tom': '#54cbba',
        'ty': '#54cbba',
        'kk': '#54cbba',
        'amu': '#54cbba',
        'yev': '#54cbba',
        'kam': '#54cbba',
        'mag': '#54cbba',
        'pri': '#54cbba',
        'sa': '#54cbba',
        'sak': '#54cbba',
        'kha': '#54cbba',
        'chu': '#54cbba'
      }
      
      return render_template('index.html', page_title = title, districts=discricts)# handle html and its variables
      #return render_template('index.html', page_title = title, weather = weather, news_list = news_list)# handle html and its variables

  @app.route('/layer/') # decorator
  def layer1():#function name is view
      title = "Republics of Russia"
      discricts =  {"cfo": '#000000',
        "szfo": '#54cbba',
        "yfo": '#f9768e',
        "skfo": '#9a5597',
        "pfo": '#30cb05',
        "urfo": '#682a43',
        "sfo": '#16acdb',
        "dfo": '#fbc520',
        'bel': '#54cbba',
        'bry': '#54cbba',
        'vla': '#54cbba',
        'vor': '#54cbba',
        'iva': '#54cbba',
        'klu': '#54cbba',
        'kos': '#54cbba',
        'krs': '#54cbba',
        'lip': '#54cbba',
        'mos': '#54cbba',
        'mow': '#54cbba',
        'orl': '#54cbba',
        'rya': '#54cbba',
        'smo': '#54cbba',
        'tam': '#54cbba',
        'tve': '#54cbba',
        'tul': '#54cbba',
        'yar': '#54cbba',
        'ark': '#54cbba',
        'vlg': '#54cbba',
        'kgd': '#54cbba',
        'kr': '#f9768e',
        'ko': '#54cbba',
        'len': '#54cbba',
        'mur': '#54cbba',
        'nen': '#54cbba',
        'ngr': '#54cbba',
        'psk': '#54cbba',
        'spe': '#54cbba',
        'ad': '#f9768e',
        'ast': '#54cbba',
        'vgg': '#54cbba',
        'kl': '#f9768e',
        'kda': '#54cbba',
        'sev': '#54cbba',
        'kry': '#f9768e',
        'ros': '#54cbba',
        'da': '#f9768e',
        'in': '#f9768e',
        'kb': '#f9768e',
        'kc': '#f9768e',
        'se': '#f9768e',
        'sta': '#54cbba',
        'ce': '#f9768e',
        'ba': '#f9768e',
        'kir': '#54cbba',
        'me': '#f9768e',
        'mo': '#f9768e',
        'niz': '#54cbba',
        'ore': '#54cbba',
        'pnz': '#54cbba',
        'per': '#54cbba',
        'sam': '#54cbba',
        'sar': '#54cbba',
        'ta': '#f9768e',
        'ud': '#f9768e',
        'uly': '#54cbba',
        'cu': '#f9768e',
        'kgn': '#54cbba',
        'sve': '#54cbba',
        'tyu': '#54cbba',
        'khm': '#54cbba',
        'che': '#54cbba',
        'yan': '#54cbba',
        'alt': '#54cbba',
        'al': '#f9768e',
        'bu': '#f9768e',
        'zab': '#54cbba',
        'irk': '#54cbba',
        'kem': '#54cbba',
        'kya': '#54cbba',
        'nvs': '#54cbba',
        'oms': '#54cbba',
        'tom': '#54cbba',
        'ty': '#f9768e',
        'kk': '#f9768e',
        'amu': '#54cbba',
        'yev': '#54cbba',
        'kam': '#54cbba',
        'mag': '#54cbba',
        'pri': '#54cbba',
        'sa': '#f9768e',
        'sak': '#54cbba',
        'kha': '#54cbba',
        'chu': '#54cbba'
      }
      
      return render_template('layer1.html', page_title = title, districts=discricts)# handle html and its variables
  return app
  